services:
  ufape-crawler-golang:
    container_name: ufape-crawler-golang
    image: nettojulio/ufape-crawler-golang:latest
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - app-private-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-private-network:
    driver: bridge
    name: app-private-network
